# Please read "/azure-active-directory/README.md" to fill the placeholders in this file:
# "<tenant-id>", "<resource-server-2-client-id>", "<resource-server-2-client-secret>".
server:
  port: 8082
spring:
  security:
    oauth2:
      client:
        provider:
          azure-active-directory:
            issuer-uri: https://login.microsoftonline.com/<tenant-id>/v2.0 # Refs: https://docs.spring.io/spring-security/site/docs/current/reference/html5/#webflux-oauth2-login-openid-provider-configuration
        registration:
          resource-server-2-resource-server-3:
            client-id: <resource-server-2-client-id>
            client-secret: <resource-server-2-client-secret>
            authorization-grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
            scope: api://<resource-server-3-client-id>/resource-server-3.scope-1
      resourceserver:
        jwt:
          jwk-set-uri: https://login.microsoftonline.com/<tenant-id>/discovery/v2.0/keys
          issuer-uri: https://login.microsoftonline.com/<tenant-id>/v2.0
          audience: <resource-server-2-client-id>
