spring:
  cloud:
    azure:
      profile:
        tenant-id: ${tenant-id}
      credential:
        client-id: ${client-id}
        client-secret: ${client-secret}
      keyvault:
        secret:
          property-source-enabled: true
          endpoint: ${endpoint}
