spring:
  cloud:
    azure:
      tenant-id: <tenant-id>
      client-id: <client-id>
      client-key: <client-key>
      keyvault:
        secret:
          property-source-enabled: true
          endpoint: <endpoint>
