spring:
  cloud:
    stream:
      function:
        definition: queueConsume;queueSupply;topicConsume;topicSupply;
      bindings:
        topicConsume-in-0:
          destination: [servicebus-topic-1-name]
          group: [topic-subscription-name]
        topicSupply-out-0:
          destination: [servicebus-topic-1-name]
        queueConsume-in-0:
          binder: servicebus-2
          destination: [servicebus-queue-1-name]
        queueSupply-out-0:
          binder: servicebus-2
          destination: [servicebus-queue-1-name]
      binders:
        servicebus-1:
          type: servicebus
          default-candidate: true
          environment:
            spring:
              cloud:
                azure:
                  servicebus:
                    connection-string: [servicebus-namespace-1-connection-string]
        servicebus-2:
          type: servicebus
          default-candidate: false
          environment:
            spring:
              cloud:
                azure:
                  servicebus:
                    connection-string: [servicebus-namespace-2-connection-string]
      servicebus:
        bindings:
          topicSupply-out-0:
            producer:
              entity-type: topic
          queueSupply-out-0:
            producer:
              entity-type: queue
      poller:
        initial-delay: 0
        fixed-delay: 1000