#spring:
#  cloud:
#    stream:
#      function:
#        definition: consume1;supply1;consume2;supply2
#      bindings:
#        consume1-in-0:
#          destination: [servicebus-queue-1-name]
#        supply1-out-0:
#          destination: [servicebus-queue-1-name-same-as-above]
#        consume2-in-0:
#          binder: servicebus-2
#          destination: [servicebus-queue-2-name]
#        supply2-out-0:
#          binder: servicebus-2
#          destination: [servicebus-queue-2-name-same-as-above]
#
#      binders:
#        servicebus-1:
#          type: servicebus-queue
#          default-candidate: true
#          environment:
#            spring:
#              cloud:
#                azure:
#                  servicebus:
#                    connection-string: [servicebus-namespace-1-connection-string]
#        servicebus-2:
#          type: servicebus-queue
#          default-candidate: false
#          environment:
#            spring:
#              cloud:
#                azure:
#                  servicebus:
#                    connection-string: [servicebus-namespace-2-connection-string]
#      servicebus:
#        queue:
#          bindings:
#            consume1-in-0:
#              consumer:
#                checkpoint-mode: MANUAL
#            consume2-in-0:
#              consumer:
#                checkpoint-mode: MANUAL
#      poller:
#        initial-delay: 0
#        fixed-delay: 1000
server:
  port: 8081
spring:
  cloud:
    stream:
      function:
        definition: topicConsume;topicSupply;queueConsume;queueSupply
      bindings:
        topicConsume-in-0:
          destination: yonghui-topic
          group: yonghui-subscription
        topicSupply-out-0:
          destination: yonghui-topic
        queueConsume-in-0:
          binder: servicebus-2
          destination: yonghui-queue2
        queueSupply-out-0:
          binder: servicebus-2
          destination: yonghui-queue2
      binders:
        servicebus-1:
          type: servicebus
          default-candidate: true
          environment:
            spring:
              cloud:
                azure:
                  servicebus:
                    connection-string: Endpoint=sb://yonghui-servicebus.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=ggnHRUiSbu4wpSLvWYHHW6BQfF9rORH7xQda4IW4mhk=
        servicebus-2:
          type: servicebus
          default-candidate: false
          environment:
            spring:
              cloud:
                azure:
                  servicebus:
                    connection-string: Endpoint=sb://yonghui-servicebus2.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=UAbfVMCBHQLdULvtIXLEQtk/f9fQZP0p9nMnBfUevDQ=
      servicebus:
        bindings:
          topicSupply-out-0:
            producer:
              entity-type: topic
          queueSupply-out-0:
            producer:
              entity-type: queue
      poller:
        initial-delay: 0
        fixed-delay: 1000

  profiles:
    active: manual