server:
  port: 8081

spring:
  cloud:
    azure:
# Properties like spring.cloud.azure.credential.client-id are global properties.
# Properties like spring.cloud.azure.active-directory.credential.client-id are AAD properties.
# If AAD properties is not configured, global properties will be used.
#      credential:
#        client-id:
#        client-secret:
#      profile:
#        tenant-id:
      active-directory:
        enabled: true
        credential:
          client-id: ${client-id}
          client-secret: ${client-secret}
        profile:
          tenant-id: ${tenant-id}
        app-id-uri: <Web-API-A-app-id-url>
        authorization-clients:
          graph:
            scopes:
              - https://graph.microsoft.com/User.Read
          webapiB:         # When authorization-grant-type is null, on behalf of flow is used by default
            authorization-grant-type: on_behalf_of
            scopes:
              - <Web-API-B-app-id-url>/WebApiB.ExampleScope
          webapiC:
            authorization-grant-type: client_credentials
            scopes:
              - <Web-API-C-app-id-url>/.default